### ISSUE TITLE
Components scan output issues

### ISSUE THREAD

**Issue by pes-soft** [rezasp/joomscan#12]
Hi,

Components scan output is assigned to config.php.x file scan in reports, but it should have a separate section:
```
[+] Checking sensitive config.php.x file
[++] Readable config files are not found
[++] components are not found
```
It could also have a separate "Checking components ..." line in output ( so it is logged that it has been performed ).

Thanks

**Comment by rezasp** [comment]
Hello,
Thank you for your issue.
Fixed.
Best Regards.
