### ISSUE TITLE
Show notification for HTTPS target when LWP protocol is missing

### ISSUE THREAD

**Issue by pes-soft** [rezasp/joomscan#15]
Hi,

Running joomscan against target with HTTPS, when https support ( `LWP/Protocol/https.pm` ) is not available, looks like there is Joomla detected on the target. Instead it should show some brief notification about missing https support in LWP.

Thanks

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for reporting the issue, I think `LWP` supports `HTTPS` by default and it's always available, otherwise please share us more details and feel free to send your PR.

Best Regards.

**Comment by pes-soft** [comment]
Hi,
Thank you for the feedback. `HTTPS` is provided for `LWP` by [additional protocol module](http://search.cpan.org/~oalders/LWP-Protocol-https-6.07/lib/LWP/Protocol/https.pm). Therefore it is usually a separate package on some OSes ( I've tested it on RedHat 7 and Fedora 27 ) and so it does not install by default with LWP. PR #16 has been sent to address this topic.

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for sharing information, @rezasp Please review.

Best Regards.
