### ISSUE TITLE
Use of uninitialized value in pattern match (m//) at ./joomscan.pl line 1009

### ISSUE THREAD

**Issue by f1she3** [rezasp/joomscan#3]
Hello !

I get the following warning message when running joomscan :
``
Use of uninitialized value in pattern match (m//) at ./joomscan.pl line 1009
``
 is everything normal ?
Thanks for this great tool

**Comment by rezasp** [comment]
Hello,
Thanks for your report, we are working on the new  release of this project. The new structure will be replace soon!
