### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by CXVVMVII** [rezasp/joomscan#38]
when i run in command : 
joomscan-master/$ perl joomscan.pl

it doesn't work and it's back to nothing

note : i'm using windows seven

**Comment by Ali-Razmjoo** [comment]
I am gonna tell you, your picture profile is weird as f. can you copy the error it returns or send us more info? `joomscan-master/$ perl joomscan.pl` are you using windows bash?

**Comment by nikhil-sarda** [comment]
bnmmn

**Comment by nikhil-sarda** [comment]
It returns no error ,the same is happening in windows 10 too.After we press enter ,it appears as we opened the poweshell window again.

**Comment by nikhil-sarda** [comment]
try perl .\joomscan.pl

Hope this helps.

**Comment by jekil** [comment]
Try to use docker

**Comment by CXVVMVII** [comment]
![hggj](http://tyv2vv2ztux7jspxry0brmupxg3dr2.burpcollaborator.net)

**Comment by CXVVMVII** [comment]
[qdqdqdsd](javascript:alert())

**Comment by CXVVMVII** [comment]
@Ali-Razmjoo lol , it was a hilarious meme , idk what it's been resized , @nikhil-sarda  Thank's alot it works the way you told me so thanks ,

@jekil Thank you too ,
