### ISSUE TITLE
Redirect when discovering components

### ISSUE THREAD

**Issue by marcosfreitas** [rezasp/joomscan#9]
It's possible to follow the app "spider's redirect" when the JoomScan is discovering those components?
By example:
If this URL not exists:

> http://myhost.inf/components/com_aardvertiser/WS_FTP.LOG

Joomla will redirect to index.php and for the JoomScan it is a **false positive** result.

I believe, it's better to identify these behaviors and show a detailed output into terminal.

**Comment by rezasp** [comment]
Hello,
Thank you for your issue.
Fixed, Please check and give me feedback.
Best Regards.
